test revert requirements

diff --git a/test/Dockerfile b/test/Dockerfile
--- a/test/Dockerfile
+++ b/test/Dockerfile
@@ -16,8 +16,8 @@ ENV DISPLAY=:99
 WORKDIR /tmp/depthai-experiments
 ENTRYPOINT ["sh", "-c", "\
     if [ -z \"$PLATFORM\" ]; then \
-        echo 'Error: PLATFORM environment variable is required' && \
-        exit 1; \
+    echo 'Error: PLATFORM environment variable is required' && \
+    exit 1; \
     fi && \
     python -u test/gen3_script_tester.py \
     --environment-variables DEPTHAI_PLATFORM=${PLATFORM} \
