docker python version fix

diff --git a/test/Dockerfile b/test/Dockerfile
--- a/test/Dockerfile
+++ b/test/Dockerfile
@@ -1,7 +1,9 @@
 ARG PYTHON_VERSION
-RUN [ -z "$PYTHON_VERSION" ] && echo "PYTHON_VERSION build argument is required" && exit 1 || true
-FROM python:${PYTHON_VERSION}
+FROM alpine AS arg-check
+ARG PYTHON_VERSION
+RUN [ -n "$PYTHON_VERSION" ] || (echo "PYTHON_VERSION build argument is required" && exit 1)
 
+FROM python:${PYTHON_VERSION}
 ARG PLATFORM
 ARG DAI_VERSION
 
