move the entrypoint back to docker file

diff --git a/test/Dockerfile b/test/Dockerfile
--- a/test/Dockerfile
+++ b/test/Dockerfile
@@ -14,3 +14,13 @@ ENV DISPLAY=:99
 
 # Setup Test Command
 WORKDIR /tmp/depthai-experiments
+ENTRYPOINT ["sh", "-c", "\
+    if [ -z \"$PLATFORM\" ]; then \
+        echo 'Error: PLATFORM environment variable is required' && \
+        exit 1; \
+    fi && \
+    python -u test/gen3_script_tester.py \
+    --environment-variables DEPTHAI_PLATFORM=${PLATFORM} \
+    --virtual-display \
+    --path ./neural-networks/advanced-examples/object-detection/mobile-object-localizer \
+    ${DAI_VERSION:+--depthai-version ${DAI_VERSION}}"]
